### ISSUE TITLE
Crash on start: smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available'

### ISSUE THREAD

**Issue by markstos** [emlun/yubikey-oath-dmenu#11]
I installed this on Arch and am getting the mentioned error. Maybe there is a missing dependency or a service that is expected to be running?

**Comment by emlun** [comment]
The OATH feature in the YubiKey Manager library requires the `pcscd` service to be running, so probably that?

**Comment by markstos** [comment]
That was it. Resolved like this:

```
yay acsccid
sudo systemctl enable pcscd.service
sudo systemctl start pcscd.service 
sudo systemctl status pcscd.service
```

**Comment by markstos** [comment]
I was beginning to suspect my 11 year old T400 laptop was at fault. :)
