### ISSUE TITLE
wish: Support `wtype` instead of `xdotool` under Wayland

### ISSUE THREAD

**Issue by markstos** [emlun/yubikey-oath-dmenu#12]
This tool should work fairly well under Wayland because `dmenu` can be symlinked to the Wayland-native `wofi` tool.

However, the `--type` option calls `xdotool`, which is X11-specific. Logic could be added which checks if the `WAYLAND_DISPLAY` environment variable is set.

If so, `[wtype](https://github.com/atx/wtype)` would be called instead of `xdotool`.

Docs would need to be updated to note that `wtype` should be installed if you are using Wayland and want to use the `--type` option.

**Comment by emlun** [comment]
Fixed by #13. Thanks!

**Comment by markstos** [comment]
I hadn't actually tested my patch under Wayland until tonight. I'm confirming it works.
