### ISSUE TITLE
Broken when `wtype` installed, but X11 is used

### ISSUE THREAD

**Issue by markstos** [emlun/yubikey-oath-dmenu#15]
Recent code assumes that if `wtype` is installed, then `Wayland` being used, which is an incorrect assumption.   

It breaks when `wtype` is installed but the environment is X11. 

Instead, you must check for the appropriate environment variable to indicate a Wayland environment and also that `wtype` is installed.

**Comment by emlun** [comment]
Oh yeah, of course, silly me. I did consider this, but decided it seemed unlikely someone would have `wtype` installed without using Wayland. Guess I was completely wrong on that...

**Comment by markstos** [comment]
I'm evaluating Sway, but use i3 as my stable desktop. So I installed `wtype` for Sway, but still use `i3` regularly. It's helpful if I can use the same fork of this project in both environments.

**Comment by emlun** [comment]
Yeah, definitely. Thanks for the patch!
