### ISSUE TITLE
Unix philosophy

### ISSUE THREAD

**Issue by ign0tus** [emlun/yubikey-oath-dmenu#17]
Another thought that crossed my mind:

The [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) says:
> - Write programs that do one thing and do it well.
> - Write programs to work together.
> - Write programs to handle text streams, because that is a universal interface.

So wouldn't it make more sense to completely remove the clipboard and typing functionality, write the output only to stdout and shift the composition of the tools to the user?

```sh
yubikey-oath-dmenu | wl-copy --paste-once
```

**Comment by emlun** [comment]
I get where you're coming from, but no, that would not make more sense. That wouldn't be too far removed from just shell-scripting the entire thing with `ykman oath code`, which is actually where this program originally started (see 90cd51328d3bd5cc0e0e899c9024e7472b6cbc47). Unix philosophy is great for plumbing, terminal applications and data transformation (as attested by the popularity of microservices), but not necessarily for end-user interfaces.

What does make sense, though, is to add an _option_ to only write the OTP to stdout. That is planned for release 0.12.0, a few weeks from now, based on your earlier feedback. :slightly_smiling_face: It'll come along with restructuring the options a bit to be more explicit about what to do. This way, all the clipboard/typing and desktop-specific things can be made optional dependencies, as they will all be explicit opt-in behaviours.

**Comment by ign0tus** [comment]
I see. Thanks for clarifying. After your explanation, I totally agree with you.
