### ISSUE TITLE
Bug: Typing into XWayland windows fails

### ISSUE THREAD

**Issue by markstos** [emlun/yubikey-oath-dmenu#18]
While typing in Wayland has approved, now typing into XWayland windows doesn't work.

Ugh.

It appears we need use `wtype` if the active window is a Wayland window, and `xdotool type` if it's an XWayland window.

For a window manager like Sway, you could figure out the active window type with scripting, but I don't know if there's a general solution for all Wayland compositors or not.

I'll probably give up on having typing work and switch to putting the codes on the clipboard instead. 

This could be possibly be fixed in `wtype` instead. Looks like it's already Issue #1 in `wtype`:
https://github.com/atx/wtype/issues/1

**Comment by markstos** [comment]
On the plus side, I confirmed that `--clipboard-cmd wl-copy` works on Wayland to copy to the clipboard.

**Comment by emlun** [comment]
Hm, ok. So I guess the scenario here is that you have a Wayland environment, in which you have both XWayland and native Wayland windows? Meaning `WAYLAND_DISPLAY` will be set for both kinds of windows?

**Comment by markstos** [comment]
Correct.  Wayland typically launches `XWayland` as a proxy for X11 apps. I confirmed by launching a Wayland-native terminal and X11-native terminal under XWayland reviewed the output of `env` in both to confirm that WAYLAND_DISPLAY was set in both cases.

**Comment by emlun** [comment]
Ok. In that case I don't know if there's much we can do in this script, it might be down to assembling the `yubikey-oath-dmenu` command dynamically in the window manager settings like you mentioned above. I'm not too keen on adding window manager introspection as an integrated feature, though mostly because I'm not familiar with how that would work.

**Comment by markstos** [comment]
Let's close this in favor of having `wtype` fix the issue upstream.

**Comment by markstos** [comment]
Using `ydotool` may be a better solution for typing. It is not specific to Wayland or X11. Rather, it emulates an input device, like a keyboard. Thus, it can "type" into both Wayland, XWayland, X11.

**Comment by emlun** [comment]
Thanks for the tip! I'll look into that for the next few updates.
