### ISSUE TITLE
No module named 'ykman.driver_ccid' with yubikey-manager version > 4.x

### ISSUE THREAD

**Issue by stibi** [emlun/yubikey-oath-dmenu#19]
Hi,
looks like the `driver_ccid` is gone with the latest `ykman` module from the yubikey-manager.

```
❯ /usr/bin/yubikey-oath-dmenu
Traceback (most recent call last):
  File "/usr/bin/yubikey-oath-dmenu", line 25, in <module>
    import ykman.driver_ccid
ModuleNotFoundError: No module named 'ykman.driver_ccid'
```

Working on the fix right now.

**Comment by emlun** [comment]
Thank you, that would be wonderful. In case it helps: I think `ykman.driver_ccid.open_devices()` has been approximately replaced by `yubikit.pcsc.list_devices()`, and `ykman.oath.OathController` by `yubikit.oath.OathSession`, but the the latter is not quite a drop-in replacement.

**Comment by markstos** [comment]
Thanks @stibi. I've subscribed for updates on this.
