### ISSUE TITLE
Allow arguments passed to dmenu

### ISSUE THREAD

**Issue by agherzan** [emlun/yubikey-oath-dmenu#2]
Currently, the script hardcodes arguments passed to dmenu. For example `-p`. Let the user invoke this script with custom arguments for dmenu. Ex. `-sb`.

**Comment by emlun** [comment]
Hi! Sorry, I had completely missed this - apparently I wasn't watching the repo.

That sounds like a fair idea, I'll take a look at it.

**Comment by emlun** [comment]
Added in #6, thanks @relatev!
