### ISSUE TITLE
wish: improve "Aborted by user" diagnostic - detect "No Yubikey found" case.

### ISSUE THREAD

**Issue by markstos** [emlun/yubikey-oath-dmenu#22]
I have a Yubikey 5 which supports TOTP codes and a basic Yubikey which supports only U2F.

Today I had the wrong one plugged in but didn't realize the problem and this happened:

```
 yubikey-oath-dmenu --menu-cmd 'dmenu -p "Credentials" -i' --clipboard-cmd wl-copy --c
lipboard

Aborted by user.
```

I guessed wrong about what this meant and spent some time downgrading `yubikey-manager` only to find that didn't fix it. 

It would be great if it's possible to emit a more specific error in this case like "No supported Yubikey found".

**Comment by emlun** [comment]
Good idea! I just pushed branch [`no-yubikey-error`](https://github.com/emlun/yubikey-oath-dmenu/tree/no-yubikey-error) trying this out. Can you have a look and see how that works for you?

**Comment by markstos** [comment]
I tested the branch. Works great. Thank you!
